name: branlette collective
on: push
jobs:
  build:
    name: Package AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf agathe.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "agathe.war"
        target: "/opt/tomcat/webapps"

  deploy:
    name: SAV IPFS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf agathe.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add agathe.war > ipfs_key.txt
        shell: alpine.sh --root {0}


  setup_and_backup:
    name: Setup SSH and Backup Database
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      
      - uses: actions/checkout@v2
      
      
      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
      
      
      - name: Create SSH Tunnel
        run: |
          ssh -i ~/.ssh/id_rsa -L 3307:127.0.0.1:3306 admin@${{ secrets.HOST_DNS }} -N &
          SSH_TUNNEL_PID=$!
          sleep 10
          # original from @ReeZeMvp
          if ps -p $SSH_TUNNEL_PID > /dev/null; then
            echo "SSH tunnel established, PID: $SSH_TUNNEL_PID"
          else
            echo "SSH tunnel failed"
            exit 1    
          fi
      
 
      - name: Dump MySQL Database
        env:
          MYSQL_PWD: ${{ secrets.MYSQLDUMP_PASSWORD }}
        run: |
          mysqldump -ucnam -h127.0.0.1 -P3307 --password="${MYSQL_PWD}" films > save_agathe.sql
          if [ $? -ne 0 ]; then
            echo "Failed to dump MySQL"
            exit 1
          fi
      

      - name: Kill SSH Tunnel
        if: always()
        run: |
          kill $SSH_TUNNEL_PID || echo "SSH tunnel fin."


      - name: Add to IPFS
        run: |
          wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
          tar xvfz go-ipfs_v0.9.1_linux-amd64.tar.gz
          cd go-ipfs
          sudo bash install.sh
          sleep 5
          ipfs init
          ipfs daemon &
          sleep 5
          # rompichhh
          ipfs add save_agathe.sql > ipfs_key2

      - name: Notification Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ipfs_key2=$(cat ipfs_key2.txt | awk '{print $2}')
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \":tada: Agathe: Le workfl-owo IPFS est finito pipo. Clé IPFS .war: $ipfs_key ;Clé IPFS SQL : $ipfs_key2 :tada:\"}" $DISCORD_WEBHOOK
